### Register
POST http://localhost:3000/api/v1.0/auth/register
Content-Type: application/json
Accept: application/json

{
    "name": "Nonos",
    "username": "nono",
    "password": "secret123"
}

### Login
POST http://localhost:3000/api/v1.0/auth/login
Content-Type: application/json
Accept: application/json

{
    "username": "nono",
    "password": "secret123"
}

### Get Profile
GET http://localhost:3000/api/v1.0/user/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTm9ub3MiLCJ1c2VybmFtZSI6Im5vbm8iLCJleHAiOjE1MDAwLCJpc3MiOiJ0ZXN0In0.BxXrGhBPjoHbjFCN384-fyUpB6BF0Zww7rDAcgwCiY8