version: "3.9"
services: 
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
      TZ: "Asia/Jakarta"
      PGTZ: "Asia/Jakarta"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sample_api
    volumes: 
      - type: volume
        source: local
        target: /var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5555:8080"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
      PGADMIN_LISTEN_PORT: 8080

volumes: 
  local:
    driver: local

networks: 
  default:
    driver: bridge