version: "3.9"
services: 

  gin-api-sample-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gin-api-sample-dev
    ports: 
      - "3000:3000"
    volumes: 
        - ../:/app
    restart: on-failure
    networks: 
      - default

volumes: 
  local:
    driver: local

networks: 
  default:
    driver: bridge